use qlty_coverage::parser::Lcov;
use qlty_coverage::Parser;

#[test]
fn results() {
    let input = include_str!("fixtures/lcov/sample.lcov");
    insta::assert_yaml_snapshot!(Lcov::new().parse_text(input).unwrap(), @r#"
    - path: formatter.js
      hits:
        - "1"
        - "1"
        - "1"
        - "1"
        - "1"
        - "1"
        - "1"
        - "1"
        - "-1"
        - "1"
        - "1"
        - "-1"
        - "-1"
        - "1"
        - "5"
        - "-1"
        - "-1"
        - "1"
        - "2"
        - "1"
        - "1"
        - "1"
        - "-1"
        - "0"
        - "-1"
        - "-1"
        - "-1"
        - "1"
        - "2"
        - "-1"
        - "2"
        - "2"
        - "0"
        - "-1"
        - "-1"
        - "2"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "2"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "2"
    "#);
}
