name: Plugin Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "qlty-plugins/**"
      - "qlty-config/**"
      - "qlty-check/src/tool/**"
      - ".github/workflows/plugins.yml"
  pull_request:
    paths:
      - "qlty-plugins/**"
      - "qlty-config/**"
      - "qlty-check/src/tool/**"
      - ".github/workflows/plugins.yml"

permissions:
  actions: write
  contents: read
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    if: github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true
    env:
      QLTY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: plugins/package-lock.json

      - name: Generate cache key
        run: echo "CACHE_MONTH=$(date +'%Y-%m')" >> $GITHUB_ENV

      - name: Cache qlty tools
        uses: actions/cache@v4
        with:
          path: ~/.qlty
          key: ${{ runner.os }}-qlty-${{ env.CACHE_MONTH }}-v1

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        if: contains(matrix.os, 'macos')

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.7
        if: contains(matrix.os, 'windows')

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build
        env:
          RUST_BACKTRACE: 1

      - name: Move qlty into PATH
        run: echo "${{ github.workspace }}/target/debug" >> $GITHUB_PATH

      - name: Check qlty version
        run: qlty --version

      - name: Run plugins tests
        working-directory: plugins
        run: |
          npm ci
          npm test golang
